

  config:
      import:
        - "accounts_qa.yml"
        - "accounts_prod.yml"
  profiles:
      active:
        - "qa"



build:
  version: 1.0

accounts:
  message: "Welcome to the Accounts Service"
  contact-details:
    email: "BkM9g@example.com"
    name: "Accounts Team"
  onCallSupport:
     -(+91) 54646436565
     -(+91) 54646436565


