
build:
  version: "1.0"

card:
  message: "Welcome to the QA Service"
  contact-details:
    email: "BkM9g@example.com"
    name: "Card Team"
  onCallSupport:
    -(+91) 54646436565
    -(+91) 54646436565

