spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loan:
  message: "Welcome to the prod Service"
  contact-details:
    email: "BkM9g@example.com"
    name: "Card Team"
  onCallSupport:
    -(+91) 54646436565
    -(+91) 54646436565

